#!/usr/bin/env bash
# Materialize the cached native dev environment (LATCH-3).
#
#   just setup        -> runs only when the fingerprint of flake.lock +
#                        rust-toolchain.toml + Cargo manifests/lock +
#                        setup version + checkout path changed, or when the
#                        cached .dev/ is missing/incomplete.
#   just setup true   -> forced refresh (the single forced-refresh command).
#
# The cold path performs at most two nix interactions, both recorded here:
#   1. `nix print-dev-env --profile .dev/gcroot` — the sourceable env file
#      plus the GC root that keeps the devShell alive across garbage
#      collections.
#   2. `nix build .#deps-dev .#deps-ci` — the immutable crane dependency
#      archives, copied (never mutated) into profile-keyed writable target
#      dirs when their fingerprints match.
# The warm path performs zero nix calls.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh disable=SC1091
source "$HERE/lib.sh"

refresh="${1:-false}"
case "$refresh" in
  true | false) ;;
  *)
    lk_fail "setup: usage: just setup [refresh] where refresh is 'true' or 'false' (forced refresh: just setup true)"
    ;;
esac

cd "$LK_ROOT"

fingerprint="$(lk_fingerprint)" || lk_fail "setup: cannot compute fingerprint (required inputs missing under $LK_ROOT)"

if [[ "$refresh" != true &&
  -f "$LK_ROOT/.dev/env" &&
  -f "$LK_ROOT/.dev/fingerprint" &&
  -e "$LK_ROOT/.dev/gcroot" &&
  "$(cat "$LK_ROOT/.dev/fingerprint")" == "$fingerprint" ]]; then
  echo "setup: cached dev environment is current (fingerprint=$fingerprint)"
  echo "setup: zero nix calls performed; force a rebuild with 'just setup true'"
  exit 0
fi

# ---- cold path --------------------------------------------------------------
start_ns="$(date +%s%N)"
mkdir -p "$LK_ROOT/.dev"
tmpdir="$(mktemp -d "$LK_ROOT/.dev/.setup.XXXXXX")"
trap 'rm -rf "$tmpdir"' EXIT

if [[ "$refresh" == true ]]; then
  echo "setup: forced refresh requested (just setup true)"
fi
echo "setup: materializing dev environment (nix print-dev-env -> .dev/env, GC root -> .dev/gcroot)..."

# Nix call 1/2: sourceable environment + GC-rooted profile in one evaluation.
nix print-dev-env --profile "$LK_ROOT/.dev/gcroot" >"$tmpdir/env.raw"

# The nix-generated env creates a throwaway mktemp dir for NIX_BUILD_TOP on
# every source; recipes never run inside a nix build sandbox, so drop those
# exports instead of leaking one temp dir per invocation.
grep -vE '^export (NIX_BUILD_TOP|TMP|TEMP|TMPDIR|TEMPDIR)=' "$tmpdir/env.raw" >"$tmpdir/env.body"

# Source the candidate env so tools resolve *inside* it.
had_u=0
[[ $- == *u* ]] && had_u=1
set +u
# The file was just generated from nix print-dev-env (SC1091: runtime path).
# shellcheck disable=SC1091
source "$tmpdir/env.body"
[[ $had_u -eq 1 ]] && set -u

# Absolute cached tool paths recorded into the env file; recipes invoke these,
# never ambient PATH lookups and never nix.
tool_names=(cargo rustc rustfmt cargo-fmt cargo-clippy python3 shellcheck actionlint zstd just)
declare -A tool_paths=()
for tool in "${tool_names[@]}"; do
  if ! path="$(command -v "$tool")"; then
    lk_fail "setup: tool '$tool' not present in the devShell (flake.nix cached-environment outputs incomplete)"
  fi
  tool_paths[$tool]="$path"
done

# Compiler identity (rustc -vV: release, commit hash, host) feeds the
# profile-keyed target dir keys; written before any seed/target work.
"${tool_paths[rustc]}" -vV >"$tmpdir/toolchain-id"
mv "$tmpdir/toolchain-id" "$LK_ROOT/.dev/toolchain-id"

# Assemble the final env file: nix body + our metadata (including the baked
# dev-profile target-dir key for direct `cargo` use), then commit atomically.
{
  cat "$tmpdir/env.body"
  # Backticks below are literal comment text, not command substitutions.
  # shellcheck disable=SC2016
  printf '\n# --- LATCH-3 metadata (generated by `just setup`; do not edit) ---\n'
  printf '# Source this file directly for ad-hoc cargo use: source .dev/env\n'
  printf 'export LATCHKEY_SETUP_FINGERPRINT=%q\n' "$fingerprint"
  printf 'export LATCHKEY_SETUP_VERSION=%q\n' "$LK_SETUP_VERSION"
  printf 'export LATCHKEY_CHECKOUT=%q\n' "$LK_ROOT"
  printf 'export LATCHKEY_SETUP_DATE=%q\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  for tool in "${tool_names[@]}"; do
    printf 'export LATCHKEY_%s=%q\n' \
      "$(printf '%s' "$tool" | tr '[:lower:]-' '[:upper:]_')" "${tool_paths[$tool]}"
  done
  printf 'export CARGO_TARGET_DIR=%q\n' "$LK_ROOT/.dev/target/$(lk_target_key dev)"
} >"$tmpdir/env.new"

mv "$tmpdir/env.new" "$LK_ROOT/.dev/env"
echo "setup: wrote .dev/env (atomic) and .dev/gcroot (GC root)"

# Nix call 2/2: immutable crane dependency archives -> writable seed copies.
# Never mutate the nix store; a seed is copied once per target-dir key and
# only when the archive's profile tree matches the key's profile.
echo "setup: seeding profile-keyed target dirs from crane deps (skipped when fingerprints do not match)..."
if ! deps_outs="$(cd "$LK_ROOT" && nix build --no-link --print-out-paths .#deps-dev .#deps-ci)"; then
  lk_fail "setup: failed to realize .#deps-dev/.#deps-ci for the seed"
fi
mapfile -t seed_outs <<<"$deps_outs"
seed_profiles=(dev ci release)

seed_skipped=()
seed_done=()
for profile in "${seed_profiles[@]}"; do
  want_tree="$(lk_profile_dir "$profile")"
  # Match by archive content, never by output order: only seed when some
  # deps archive actually contains this profile's artifact tree.
  out=""
  for candidate in "${seed_outs[@]}"; do
    if [[ -f "$candidate/target.tar.zst" ]] &&
      tar --zstd -tf "$candidate/target.tar.zst" | awk -v want="./$want_tree/" \
        'index($0, want) == 1 { found = 1 } END { exit !found }'; then
      out="$candidate"
      break
    fi
  done
  if [[ -z "$out" ]]; then
    seed_skipped+=("$profile: no deps archive with profile tree '$want_tree' (incompatible fingerprint; no reuse promised)")
    continue
  fi
  archive="$out/target.tar.zst"
  key="$(lk_target_key "$profile")"
  dest="$LK_ROOT/.dev/target/$key"
  if [[ -f "$dest/.latchkey-seed" ]]; then
    seed_skipped+=("$profile: already seeded")
    continue
  fi
  mkdir -p "$dest"
  # Copy the archive contents once into writable storage (the store itself is
  # never mutated; modes are made usable after extraction).
  if ! tar --zstd -xf "$archive" -C "$dest" --no-same-owner --no-same-permissions; then
    rm -rf "$dest"
    lk_fail "setup: failed to unpack crane deps seed for profile '$profile'"
  fi
  chmod -R u+w "$dest"
  {
    printf 'seeded-from=%s\n' "$out"
    printf 'profile=%s\n' "$profile"
    printf 'lock=%s\n' "$(lk_sha "$LK_ROOT/Cargo.lock")"
    printf 'date=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >"$dest/.latchkey-seed"
  seed_done+=("$profile: seeded from $(basename "$out")")
done
for line in "${seed_done[@]}"; do echo "setup: seed $line"; done
for line in "${seed_skipped[@]}"; do echo "setup: seed skipped $line"; done

# Commit point: the fingerprint file is written last so an interrupted setup
# is always detected as stale (never half-trusted).
printf '%s\n' "$fingerprint" >"$LK_ROOT/.dev/fingerprint.tmp"
mv "$LK_ROOT/.dev/fingerprint.tmp" "$LK_ROOT/.dev/fingerprint"

end_ns="$(date +%s%N)"
elapsed_ms=$(((end_ns - start_ns) / 1000000))
echo "setup: materialized cached dev environment in ${elapsed_ms}ms (fingerprint=$fingerprint)"
echo "setup: toolchain: $("${tool_paths[rustc]}" -vV | sed -n '1p')"
echo "setup: target dirs: $LK_ROOT/.dev/target/<profile-key> (CARGO_TARGET_DIR baked for the dev profile)"
echo "setup: for direct cargo use: source .dev/env"
